### ISSUE TITLE
question

### ISSUE THREAD

**Issue by charles-chenzz** [pratise/mongoshake-kubernetes-operator#2]
这个operator是可以用来部署mongo shard集群吗

**Comment by pratise** [comment]
这个不是的，这个operator是为了部署阿里云的开源mongodb的迁移工具mongoshake。

如果要为了部署mongoshard集群的话，我推荐你使用开源的percona-mongodb

**Comment by charles-chenzz** [comment]
percona-mongodb是不是还得部署他自己的那个server才可以用他的operator

**Comment by pratise** [comment]
是的，不过这个基本上都全部兼容的，业务使用没有任何问题

**Comment by charles-chenzz** [comment]
有生产用例吗 我看最近还有个kubeblocks 我看percona的issue里很多人都在提bug之类的

**Comment by pratise** [comment]
目前我所知道是有公司在用的。
